a=int(input("enter:"))
if(a>85):
    print("mackbook")
elif(a>75):
    print("iphone")
elif(a>65):
    print("android")
elif(a>55):
    print("samsung")
elif(a>35):
    print("realme")
else:
    print("fail")